### ISSUE TITLE
你好 能加上过滤功能吗, 只选中特定的短信发

### ISSUE THREAD

**Issue by obrua** [d-jiang/EmailSMS#1]

**Comment by djiangnz** [comment]
1. 360短信？好像是这个名字，功能特别强大，能文能武的。
1. 什么叫选中特定的短信发

**Comment by obrua** [comment]
意思是，筛选特定内容的短信发邮件，不是所有短信都需要转发到邮件。。。

**Comment by djiangnz** [comment]
哦 是过滤电话号码 / 关键字之类的, 如果要加, 也是 6 月左右有时间
